### ISSUE TITLE
Ran into a snag installing on Raspbian 8

### ISSUE THREAD

**Issue by ronstar2820** [genebean/PiWeatherRock#18]
I had the previous Weather.com version running for years. For some reason, the Weather.com API is no longer working, so I looked for an alternative.

Found this app developed by the developer of my previous app, so I gave it a try.

I followed instructions and the install died

I see quite a few notices that the app is intended to run on Raspbian 10. I have Raspbian 8. So maybe that is my problem.

Probably not a bug, but I can't seem to change the "bug" label

![IMG_8311](https://user-images.githubusercontent.com/60288465/73130586-dc44f980-3fc0-11ea-9672-2aba97758f9f.JPG)

**Comment by genebean** [comment]
I’ll take a look today. I think the last line of output in your screenshot may be key. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
I am going to check a couple of things on my side but I also have a question for you: do you have a need to stay on Raspbian 8 or are you game to upgrade? Personally, I have done the in-place upgrades and had good success.

**Comment by ronstar2820** [comment]
Thanks for the quick response! I just formatted my card and did a fresh install of Raspbian 10. I'll report back my findings.

**Comment by genebean** [comment]
👍 Please do let me know how it goes because I do want to make sure that this works on current versions of Raspbian.

**Comment by ronstar2820** [comment]
Ok. Everything finished, but no service started on it's own. So I did "sudo systemctl status PiWeatherRock" and got the screenshot below. Also typed sudo python weather.py and got the other screenshot. Looks like weather.py can't find a module named "darksky"
![Screen Shot 2020-01-26 at 2 53 47 PM](https://user-images.githubusercontent.com/60288465/73141621-bca6e300-404b-11ea-89b3-32adc98835fd.png)
![Screen Shot 2020-01-26 at 2 54 03 PM](https://user-images.githubusercontent.com/60288465/73141624-c4668780-404b-11ea-9371-415f72a3643b.png)

**Comment by genebean** [comment]
I think I know what is up... I should be able to post something back in about 10 or 15 minutes

**Comment by ronstar2820** [comment]
Thanks!

**Comment by genebean** [comment]
I have the issue figured out, about to push an update.

**Comment by genebean** [comment]
@ronstar2820 - would you mind running the following commands for me to validate the fix?

```bash
$ cd ~/PiWeatherRock
$ git checkout fix_pyhton
$ sudo puppet apply /home/pi/PiWeatherRock/setup.pp
```

The branch I am asking you to try has the following changes:

```diff
diff --git a/setup.pp b/setup.pp
index 5a1f0a4..f7181e4 100644
--- a/setup.pp
+++ b/setup.pp
@@ -83,10 +83,9 @@ vcsrepo { '/home/pi/PiWeatherRock':
 }

 python::requirements { '/home/pi/PiWeatherRock/requirements.txt':
-  virtualenv   => '/home/pi/PiWeatherRock',
   pip_provider => 'pip3',
-  owner        => 'pi',
-  group        => 'pi',
+  owner        => 'root',
+  group        => 'root',
   cwd          => '/home/pi/PiWeatherRock',
   require      => [
     Package[ $main_packages, $piweatherrock_packages, ],
```

Once you have run the commands, I suggest you go ahead and switch back to master by running `git checkout master`.

**Comment by ronstar2820** [comment]
Will do!

**Comment by genebean** [comment]
BTW, for manual testing outside of systemd you will want to use `python3` instead of `python`

**Comment by ronstar2820** [comment]
I'm a novice at this and don't understand what you mean by python3 vs python.

Don't I just enter these commands on terminal?

Is the second line supposed to be "python" or "pyhton"

In either case I get "error: pathspec 'fix_python' did not match any file(s) known to git"

**Comment by genebean** [comment]
Oops, sorry about the assumptions!

So, you have two commands on your system: `python` runs Python version 2 whereas `python3` runs Python version 3. I am only testing against the latter since Python 2 is now end of life. 

In your terminal, you will first need to run `git fetch` and then the `git checkout fix_python` should work. Yes, the command above was a typo too.

**Comment by ronstar2820** [comment]
I get "Error: cannot open .git/FETCH HEAD: Permission denied" when I type git fetch on the terminal

**Comment by genebean** [comment]
What does `ls -la` show?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
and a few more files if I scroll more
![Screen Shot 2020-01-26 at 4 00 39 PM](https://user-images.githubusercontent.com/60288465/73142507-1069fa00-4055-11ea-9465-acea8f6034a3.png)

**Comment by genebean** [comment]
Does `git pull` work?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
No - I get "error: cannot open .git?/FETCH HEAD: Permission Denied"

**Comment by genebean** [comment]
It is acting like sudo got used somewhere... let me get back to you shortly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
I think I see the flaw in my approach to fixing the issue and why it’s causing problems. I should be able to resolve it tonight 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
Thanks! It’s no problem for me to start from scratch if need be. Whatever I can do to help make it easier for you.

**Comment by genebean** [comment]
Much appreciated 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
FYI: I started a Gitter for this project to facilitate real time chats too. I’ll be in there a little later. https://gitter.im/PiWeatherRock/community

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
@ronstar2820 if #20 doesn't actually fix your issue feel free to reopen this.

**Comment by ronstar2820** [comment]
Thanks - I’m giving it a try now

**Comment by ronstar2820** [comment]
Still the same situation. Ran install. Service doesn't startup. Checked status and get same screenshot as above and same error running weather.py where it can't find module darksky

**Comment by genebean** [comment]
Would you humor me and try the new update section of the readme?  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
Thanks - This is going to take a while. Since it didn’t work after your fix, I erased everything in PiWeatherRock. But I couldnt totally get rid of the directory, so I started again using PiWeatherRock2

Anyway, I’ll keep plugging

**Comment by genebean** [comment]
You can kill the entire directory by running `sudo rm -rf /home/pi/PiWeatherRock`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
Thanks! I’ll start over with a fresh PiWeatherRock

**Comment by ronstar2820** [comment]
Nope - still doesn't work. Same situation as before - same as above screenshots. Tried the update section of the readme. I get "no such file or directory" when I type "pi@rock:~/PiWeatherRock $ git pull"

**Comment by genebean** [comment]
Did you type `git pull` while inside your PiWeatherRock folder?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ronstar2820** [comment]
yes and no. I’ve tried it both ways

**Comment by genebean** [comment]
Mind continuing this via Gitter?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
We figured out via Gitter that he issue was the api key needed to have single quotes around it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
