### ISSUE TITLE
PiWeatherRock not working

### ISSUE THREAD

**Issue by hammiesam** [genebean/PiWeatherRock#19]
Hi!  

The original Weather Station stopped working for me as well.

I tried installing this on a fresh install of Buster, i followed all the steps, but nothing happens.

I ran sudo systemctl status PiWeatherRock and got the following:

Is there anything I can try?  Thanks!

● PiWeatherRock.service - PiWeatherRock Service
   Loaded: loaded (/etc/systemd/system/PiWeatherRock.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-01-26 06:13:44 EST; 4s ago
  Process: 11186 ExecStart=/usr/bin/python3 /home/pi/PiWeatherRock/weather.py (code=exited, status=1/FAILURE)
 Main PID: 11186 (code=exited, status=1/FAILURE)

**Comment by genebean** [comment]
Would you mind running the last line in install.sh and pasting the output here?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by genebean** [comment]
I think we found the problem in #18 and have a fix in #20 - I will post back shortly with confirmation.

**Comment by genebean** [comment]
FYI: I started a Gitter for this project to facilitate real time chats too. I’ll be in there a little later. https://gitter.im/PiWeatherRock/community

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammiesam** [comment]
Thanks Gene for fixing the problem!
