### ISSUE TITLE
Key to switch to main screen

### ISSUE THREAD

**Issue by ronstar2820** [genebean/PiWeatherRock#25]
Usage section of instructions say that "w" takes you to main screen. It does not. 

Code in Weather.py suggests that:

 "d" takes you to the main daily screen.
"h" takes you to the main hourly screen
etc

Perhaps the instructions can be edited

**Comment by genebean** [comment]
I’ll have this updated today. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
