### ISSUE TITLE
Error while installing Puppetlabs.

### ISSUE THREAD

**Issue by thebaldgeek** [genebean/PiWeatherRock#30]
On install I get the following error;

**Describe the bug**
Notice: Installing -- do not interrupt ...
/etc/puppet/modules
└─┬ camptocamp-systemd (v2.8.0)
  ├─┬ puppetlabs-inifile (v4.1.0)
  │ └── puppetlabs-translate (v2.1.0)
  └── puppetlabs-stdlib (v6.2.0)
Error: Could not parse for environment production: Syntax error at ':'; expected '}' at /home/pi/PiWeatherRock/setup.pp:64 on node wx.opto22.com
Error: Could not parse for environment production: Syntax error at ':'; expected '}' at /home/pi/PiWeatherRock/setup.pp:64 on node wx.opto22.com

**What's your setup?**
pi@raspberrypi:~/PiWeatherRock $ cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**How are you trying to launch the program?**
Program fails to install. Have not got to launching since the install fails.

**To Reproduce**
1. Run the following command; pi@raspberrypi:~/PiWeatherRock $ sudo ./install.sh wx
2. See error

**Expected behavior**
I expected the puppet install script to run cleanly.

**Comment by genebean** [comment]
The issue here is that Rasbian 8 comes with Puppet 3.x which was end of life'ed years ago. I am happy to help get you going but first have to ask: any reason why you don't upgrade to Rasbian 10?

**Comment by thebaldgeek** [comment]
Nope, no reason not to upgrade. Thanks for adding it as a 'requirement' to the readme.
Upgraded and installed fine.
Just one last question, is it possible to edit a file somewhere and NOT have it auto cycle between daily and hourly? I would like it to just constantly display daily.

**Comment by genebean** [comment]
Glad that got it! There really isn’t a way right now but I think you could add that request to #28. I think accounting for both would make sense. I’m closing this issue since it sounds fixed but feel free to reopen if needed or hit me up on Gitter
