### ISSUE TITLE
Display gets stuck on info mode? 

### ISSUE THREAD

**Issue by nickdifranco** [genebean/PiWeatherRock#37]
Really loving this app, exactly what I was looking for on my Pi with a 3.5 screen. I've noticed that the app switches to the info screen (usually accessed by hitting the "i" key) unprompted and seems to stay there until another key is pressed, or at least, way longer than I feel like it should. I don't know if it would revert on its own but I waited about 5 minutes before VNC-ing and hitting the D key to get back to the daily display. Perhaps this is intentional? 

This is on a Pi 3, Raspbian 10 (buster).

**Comment by genebean** [comment]
The timings are at https://github.com/genebean/PiWeatherRock/blob/91a934fb5d5f1bdd11c0feb74e280893e20692a2/weather.py#L869 but, basically, it should switch off info after about 5 minutes. Would you mind letting it sit for a bit longer and letting me know how long it actually takes on your device?

**Comment by nickdifranco** [comment]
Thanks for the quick reply, I actually just timed it and it was just about 5 minutes before reverting back to the daily display. So, working as intended. Guess I just got a little impatient.  Closing the issue. 

Thanks again. Like I said, exactly what I was looking for on my Pi. Cheers!

**Comment by genebean** [comment]
Really glad you like it!
