### ISSUE TITLE
Dual screen on Pi4

### ISSUE THREAD

**Issue by rawhide911** [genebean/PiWeatherRock#38]
when running PiWeatherRock on my Pi4 with dual screens it appears split between both screens, is there a way for it only to be seen on 1 screen so i can use the second screen for other uses?

**Comment by genebean** [comment]
@rawhide911 Try changing `FULLSCREEN` to `False` in config.py

**Comment by genebean** [comment]
@rawhide911 did you get things working? If not, feel free to jump into https://gitter.im/PiWeatherRock/community for some more real-time help

**Comment by rawhide911** [comment]
I did set fullscreen to False
when running WeatherRock both screens turn black and WeatherRock is seen on screen 1
but very small in the upper left corner

I am running the Pi4 with 2 Uctronics 7" touch screens

My ultimate goal is to run WeatherRock on one screen and Action Tiles on the other, I am currently
running Action Tiles on a Pi3 but would like to run both off the same Pi

Thank You for your help


________________________________

**Comment by genebean** [comment]
I was working on refactoring some stuff night before last and I think I know what is causing the issue you are seeing. I think I will have it fixed in the near future but it will still be a week or two.
