### ISSUE TITLE
Libraries will not load

### ISSUE THREAD

**Issue by ejmorgan55** [genebean/PiWeatherRock#4]
sudo apt-get install libsdl1.2-dev libsdl-ttf2.0-dev libsdl-image1.2-dev \
libsdl-mixer1.2-dev libjpeg-dev libportmidi-dev libtimedate-perl
pip install -r requirements.txt

Error code could not find any packages is displayed:

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libsdl-image1.2-devlibsdl-mixer1.2-dev
E: Couldn't find any package by glob 'libsdl-image1.2-devlibsdl-mixer1.2-dev'
E: Couldn't find any package by regex 'libsdl-image1.2-devlibsdl-mixer1.2-dev'

Any idea as to what the problem is?

**Comment by genebean** [comment]
I see you are on something Debian based but exactly what distro is this from?

**Comment by genebean** [comment]
I just did a fresh install on Raspbian 10 Lite with just the packages from the readme plus git, vim, and python3-pip and everything came up. Feel free to reopen if you have more info
