### ISSUE TITLE
What to do after installation?

### ISSUE THREAD

**Issue by son-dh** [genebean/PiWeatherRock#47]
Sorry for such a noob question, but I am trying to get PiWeatherRock displays on the LCD screen of my Rasp Pi 1 Model B (Buster Lite). I have done the config and ran the installation, but nothing happens on my CLI screen on the LCD (HDMI port is not used).

I checked the status of PiWeatherRock in systemctl, and here it gets confusing to me:
- I checked the status from the terminal screen on the LCD, it said .../weather.py (code=exited, status=1/FAILURE) . Yet when I check from my computer through SSH, the service active (running), and the failure line is not there.
- A few moments later, the reversal happened between the terminal and SSH

What obvious thing that I am missing here?

**Comment by genebean** [comment]
You will want to use at least "Raspbian Buster with desktop" for things to just work. It is possible to get things going with the Lite version but it takes a fair bit of manual work. Are you game to try the desktop version @son-dh?

**Comment by son-dh** [comment]
I was thinking that might be the reason. I will install a desktop environment on the pi then!

**Comment by genebean** [comment]
Any better @son-dh?

**Comment by son-dh** [comment]
@genebean thanks for reaching out! Yes I managed to get it working finally last weekend, and I have read the news about Dark Sky acquisition today... how irony...

Thanks for the great piece of work, though! With the social distancing, I can look at the weather without going outside :D

**Comment by genebean** [comment]
Glad to hear it! The Dark Sky stuff is a bummer but we will adapt.
